### ISSUE TITLE
Usage examples in README

### ISSUE THREAD

**Issue by jcgruenhage** [entropia/paperless-asn-qr-codes#6]

**Comment by melsenm** [comment]
when I use the command `paperless-asn-qr-codes --border 1 test.pdf`
I'll get the following error: 
_usage: paperless-asn-qr-codes [-h] start_asn output_file
paperless-asn-qr-codes: error: unrecognized arguments: --border_

What am I doing wrong?
Without the `--border` argument it works perfect

**Comment by margau** [comment]
It is possible that the current implementation with borders was not yet released to pypi.
@jcgruenhage can you have a look here?

**Comment by gparent** [comment]
What @margau says is correct, the current release on PyPi is from the same date as this repo's initial commit, which did not include the `--border` argument.

**Comment by Simon01011** [comment]
Is it possible to have the current commit to be released on PyPi? That would be great!

**Comment by jcgruenhage** [comment]
The current version has been released, the border argument should now work
